-- vim.opt.termguicolors = false
-- vim.cmd("colorscheme github_light_default")
-- vim.cmd("colorscheme gruvbox")
vim.cmd("colorscheme gruvbox-material")
-- vim.cmd("colorscheme catppuccin-macchiato")
-- vim.cmd("colorscheme monokai-pro")
-- vim.cmd("colorscheme rose-pine")
-- vim.cmd("colorscheme poimandres")
-- vim.g.gruvbox_material_better_performance = 1
-- vim.g.gruvbox_material_enable_italic = 1
-- vim.cmd("colorscheme catppuccin-latte")
-- vim.cmd.colorscheme("oxocarbon")
-- vim.cmd("colorscheme onedark_vivid")
-- vim.cmd("colorscheme gruvbox")
-- vim.cmd("colorscheme gruvbox")
-- vim.cmd "base16colorspace 256"
-- vim.cmd("colorscheme base16-tomorrow-night-eighties")
